# Generated by Django 2.0.5 on 2018-09-15 06:21

import datetime
from django.db import migrations, models
from django.utils.timezone import utc
import taggit.managers
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('taggit', '0002_auto_20150616_2121'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('date', models.DateTimeField(default=datetime.datetime(2018, 9, 15, 6, 21, 19, 603084, tzinfo=utc))),
                ('content', tinymce.models.HTMLField(verbose_name='Content')),
                ('tags', taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags')),
            ],
            options={
                'verbose_name': 'новость',
                'verbose_name_plural': 'новости',
            },
        ),
    ]
