# Generated by Django 2.0.4 on 2018-10-31 05:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_auto_20181031_1125'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'ordering': ['date'], 'verbose_name': 'новость', 'verbose_name_plural': 'новости'},
        ),
    ]
