# Generated by Django 2.0.4 on 2018-10-31 05:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='service',
            options={'verbose_name': 'услуга', 'verbose_name_plural': 'услуги'},
        ),
    ]
