# Generated by Django 2.0.4 on 2018-10-31 05:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_auto_20181031_1125'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='service',
            options={'ordering': ['name'], 'verbose_name': 'услуга', 'verbose_name_plural': 'услуги'},
        ),
    ]
