# Generated by Django 2.0.4 on 2018-08-01 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20180801_1136'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='companyinfo',
            options={'verbose_name': 'информация о компании', 'verbose_name_plural': 'информация о компании'},
        ),
        migrations.AlterField(
            model_name='companyinfo',
            name='key',
            field=models.CharField(max_length=50, verbose_name='Ключ'),
        ),
        migrations.AlterField(
            model_name='companyinfo',
            name='value',
            field=models.CharField(max_length=500, verbose_name='Значение'),
        ),
    ]
