# Generated by Django 2.0.4 on 2018-08-01 06:27

from django.db import migrations, models
import goods.models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0003_auto_20180801_1211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='good',
            name='price',
            field=models.FloatField(db_index=True, validators=[goods.models.validate_price], verbose_name='Цена, тг.'),
        ),
    ]
