# Generated by Django 2.0.4 on 2018-08-07 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0005_auto_20180803_0818'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='categories/images', verbose_name='Изображение'),
        ),
    ]
