# Generated by Django 2.0.4 on 2018-08-08 02:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0006_auto_20180807_0917'),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'страна',
                'verbose_name_plural': 'страны',
            },
        ),
        migrations.CreateModel(
            name='Manufacturer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Название')),
                ('logo_image', models.ImageField(blank=True, default=None, null=True, upload_to='manufacturers/images', verbose_name='Логотип')),
                ('country', models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='goods.Country', verbose_name='Страна происхождения')),
            ],
            options={
                'verbose_name': 'производитель',
                'verbose_name_plural': 'производители',
            },
        ),
        migrations.AlterField(
            model_name='good',
            name='category',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='goods.Category', verbose_name='Категория'),
        ),
        migrations.AddField(
            model_name='good',
            name='manufacturer',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='goods.Manufacturer', verbose_name='Производитель'),
        ),
    ]
