# Generated by Django 2.0.4 on 2018-08-08 03:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0009_auto_20180808_0916'),
    ]

    operations = [
        migrations.AlterField(
            model_name='good',
            name='manufacturer',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='goods.Manufacturer', verbose_name='Производитель'),
        ),
    ]
