# Generated by Django 2.0.4 on 2018-08-08 03:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0011_remove_good_manufacturer'),
    ]

    operations = [
        migrations.AddField(
            model_name='good',
            name='manufacturer',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='goods.Manufacturer', verbose_name='Производитель'),
        ),
    ]
