# Generated by Django 2.0.4 on 2018-08-10 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0013_auto_20180810_0812'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['level_index_field', 'name'], 'verbose_name': 'категория', 'verbose_name_plural': 'категории'},
        ),
        migrations.AddField(
            model_name='category',
            name='level_index_field',
            field=models.CharField(default='', editable=False, max_length=500, verbose_name='Индекс сложенности'),
        ),
    ]
