# Generated by Django 2.0.4 on 2018-08-15 06:51

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0028_auto_20180810_1328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='good',
            name='content',
            field=tinymce.models.HTMLField(verbose_name='Content'),
        ),
    ]
