# Generated by Django 2.0.4 on 2018-08-15 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0029_auto_20180815_1251'),
    ]

    operations = [
        migrations.AddField(
            model_name='good',
            name='reg_exp_date',
            field=models.DateField(default=None, null=True, verbose_name='Дата окончания регистрации'),
        ),
        migrations.AddField(
            model_name='good',
            name='reg_number',
            field=models.CharField(default=None, max_length=50, null=True, verbose_name='Регистрационное свидетельство'),
        ),
    ]
