# Generated by Django 2.0.4 on 2018-08-15 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0030_auto_20180815_1749'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='good',
            name='price',
        ),
    ]
