# Generated by Django 2.0.5 on 2019-03-12 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companyinfo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyinfo',
            name='value',
            field=models.TextField(max_length=500, verbose_name='значение параметра'),
        ),
    ]
