# Generated by Django 2.0.5 on 2019-03-12 21:59

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('companyinfo', '0002_auto_20190313_0356'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyinfo',
            name='value',
            field=tinymce.models.HTMLField(verbose_name='Value'),
        ),
    ]
