# Generated by Django 2.0.5 on 2019-03-12 22:01

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('companyinfo', '0003_auto_20190313_0359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyinfo',
            name='value',
            field=tinymce.models.HTMLField(verbose_name='Значение параметра'),
        ),
    ]
